In [17]:
# This Python 3 environment comes with many helpful analytics libraries installed
# It is defined by the kaggle/python Docker image: https://github.com/kaggle/docker-python
# For example, here's several helpful packages to load

import numpy as np # linear algebra
import pandas as pd # data processing, CSV file I/O (e.g. pd.read_csv)

# Input data files are available in the read-only "../input/" directory
# For example, running this (by clicking run or pressing Shift+Enter) will list all files under the input directory

import os
for dirname, _, filenames in os.walk('/kaggle/input'):
    for filename in filenames:
        print(os.path.join(dirname, filename))

# You can write up to 5GB to the current directory (/kaggle/working/) that gets preserved as output when you create a version using "Save & Run All" 
# You can also write temporary files to /kaggle/temp/, but they won't be saved outside of the current session

/kaggle/input/result-england1516/result_england1516.csv
/kaggle/input/epl-data/totalengland.csv
/kaggle/input/soccer/database.sqlite


In [18]:
import tensorflow as tf
import numpy as np
from pandas.io.parsers import read_csv

model = tf.compat.v1.global_variables_initializer()
data = read_csv('/kaggle/input/epl-data/totalengland.csv', sep=',')
xy = np.array(data, dtype=np.float32)
print(xy)

[[ 70.  45.  45. ...  37.  41.  80.]
 [ 70.  60.  56. ...  33.  36.  71.]
 [ 70.  60.  55. ...  33.  27.  71.]
 ...
 [ 56.  51.  54. ...  51. -18.  35.]
 [ 48.  74.  72. ...  53. -25.  33.]
 [ 52.  53.  53. ...  73. -31.  30.]]


In [19]:
x_data = xy[:, 0:-1]
y_data = xy[:,[-1]]
print(x_data)

[[ 70.  45.  45. ...  78.  37.  41.]
 [ 70.  60.  56. ...  69.  33.  36.]
 [ 70.  60.  55. ...  60.  33.  27.]
 ...
 [ 56.  51.  54. ...  33.  51. -18.]
 [ 48.  74.  72. ...  28.  53. -25.]
 [ 52.  53.  53. ...  42.  73. -31.]]


In [20]:
tf.compat.v1.disable_eager_execution()
X = tf.compat.v1.placeholder(tf.float32, shape=[None,14])
Y = tf.compat.v1.placeholder(tf.float32, shape=[None, 1])
W = tf.Variable(tf.random.normal([14,1]), name="weight")
b = tf.Variable(tf.random.normal([1]), name="bias")

In [21]:
hypothesis = tf.matmul(X,W) + b

In [22]:
cost = tf.reduce_mean(tf.square(hypothesis - Y))

In [23]:
optimizer = tf.compat.v1.train.GradientDescentOptimizer(learning_rate=0.000005)
train = optimizer.minimize(cost)

In [24]:
sess = tf.compat.v1.Session()
sess.run(tf.compat.v1.global_variables_initializer())

In [25]:
for step in range(100001):
    cost_, hypo_, _=sess.run([cost,hypothesis,train], feed_dict={X:x_data, Y:y_data})
    if step % 500 == 0 :
        print("#", step, "cost: ", cost_)
        print("-total point: ", hypo_[0])

# 0 cost:  11148.105
-total point:  [-41.033672]
# 500 cost:  288.99332
-total point:  [63.916237]
# 1000 cost:  147.86066
-total point:  [70.815056]
# 1500 cost:  87.08135
-total point:  [74.78616]
# 2000 cost:  58.172184
-total point:  [77.09043]
# 2500 cost:  43.10178
-total point:  [78.44432]
# 3000 cost:  34.612682
-total point:  [79.24863]
# 3500 cost:  29.513771
-total point:  [79.73227]
# 4000 cost:  26.274014
-total point:  [80.027565]
# 4500 cost:  24.10174
-total point:  [80.21153]
# 5000 cost:  22.56337
-total point:  [80.329254]
# 5500 cost:  21.41153
-total point:  [80.40706]
# 6000 cost:  20.501032
-total point:  [80.46056]
# 6500 cost:  19.744843
-total point:  [80.49895]
# 7000 cost:  19.090075
-total point:  [80.52752]
# 7500 cost:  18.50394
-total point:  [80.54936]
# 8000 cost:  17.966082
-total point:  [80.56674]
# 8500 cost:  17.463581
-total point:  [80.58071]
# 9000 cost:  16.988089
-total point:  [80.59208]
# 9500 cost:  16.534195
-total point:  [80.60134]
# 10

# 80500 cost:  0.46969682
-total point:  [80.20654]
# 81000 cost:  0.45827278
-total point:  [80.204185]
# 81500 cost:  0.44716895
-total point:  [80.202156]
# 82000 cost:  0.4362639
-total point:  [80.20016]
# 82500 cost:  0.42571524
-total point:  [80.198235]
# 83000 cost:  0.41533586
-total point:  [80.19625]
# 83500 cost:  0.40529415
-total point:  [80.194046]
# 84000 cost:  0.3954404
-total point:  [80.19219]
# 84500 cost:  0.3858468
-total point:  [80.190315]
# 85000 cost:  0.37649512
-total point:  [80.18845]
# 85500 cost:  0.36733484
-total point:  [80.18646]
# 86000 cost:  0.35846823
-total point:  [80.18412]
# 86500 cost:  0.34974545
-total point:  [80.18228]
# 87000 cost:  0.341253
-total point:  [80.1804]
# 87500 cost:  0.33299044
-total point:  [80.17857]
# 88000 cost:  0.3248606
-total point:  [80.17674]
# 88500 cost:  0.31703135
-total point:  [80.17501]
# 89000 cost:  0.3093306
-total point:  [80.17327]
# 89500 cost:  0.30181918
-total point:  [80.1715]
# 90000 cost:  0

In [26]:
saver = tf.compat.v1.train.Saver()
save_path = saver.save(sess, "./saved.cpkt")
print("model saved")

model saved


In [27]:
saver = tf.compat.v1.train.Saver()
model = tf.compat.v1.global_variables_initializer()

In [28]:
speed = float(input('speed: '))
play_passing = float(input('play_passing: '))
creation_passing = float(input('creation_passing: '))
creation_crossing = float(input('creation_crossing: '))
creation_shooting = float(input('creation_shooting: '))
pressure = float(input('pressure: '))
aggression = float(input('agression: '))
teamwidth = float(input('teamwidth: '))
wins = float(input('wins: '))
draws = float(input('draws: '))
loses = float(input('loses: '))
goals_scored = float(input('goals_scored: '))
goals_against = float(input('goals_against: '))
goal_diff = float(input('goal_diff: '))

speed: 63
play_passing: 60
creation_passing: 47
creation_crossing: 64
creation_shooting: 46
pressure: 58
agression: 65
teamwidth: 55
wins: 23
draws: 12
loses: 3
goals_scored: 68
goals_against: 36
goal_diff: 32


In [29]:
with tf.compat.v1.Session() as sess: 
    sess.run(model)
    save_path = "./saved.cpkt"
    saver.restore(sess, save_path)

    data = ((speed, play_passing, creation_passing, creation_crossing, creation_shooting, pressure, aggression, teamwidth, wins, draws, loses, goals_scored, goals_against, goal_diff),)
    arr = np.array(data, dtype=np.float32)

    x_data = arr[0:14]
    dict = sess.run(hypothesis, feed_dict={X:x_data})
    print(dict[0])

[80.94755]
